import AmazonMusicIcon from "../../../../../assets/storeIcon/amazonMusic.svg";
import AnghamiIcon from "../../../../../assets/storeIcon/anghami.svg";
import AppleMusicIcon from "../../../../../assets/storeIcon/appleMusic.svg";
import AudibleMagicIcon from "../../../../../assets/storeIcon/audibleMagic.svg";
import AwaIcon from "../../../../../assets/storeIcon/awa.svg";
import BeatportIcon from "../../../../../assets/storeIcon/beatport.svg";
import BoomplayIcon from "../../../../../assets/storeIcon/boomplay.svg";
import ClaroMusicIcon from "../../../../../assets/storeIcon/claroMusic.svg";
import DeezerIcon from "../../../../../assets/storeIcon/deezer.svg";
import DouYinIcon from "../../../../../assets/storeIcon/douYin.svg";
import FloIcon from "../../../../../assets/storeIcon/flo.svg";
import IHeartIcon from "../../../../../assets/storeIcon/iHeart.svg";
import JooxIcon from "../../../../../assets/storeIcon/joox.svg";
import KDigitalIcon from "../../../../../assets/storeIcon/kDigital.svg";
import KanjianIcon from "../../../../../assets/storeIcon/kanjian.svg";
import KkboxIcon from "../../../../../assets/storeIcon/kkbox.svg";
import LickdIcon from "../../../../../assets/storeIcon/lickd.svg";
import LissenIcon from "../../../../../assets/storeIcon/lissen.svg";
import MassiveIcon from "../../../../../assets/storeIcon/massive.svg";
import MetaIcon from "../../../../../assets/storeIcon/meta.svg";
import MixCloudIcon from "../../../../../assets/storeIcon/mixCloud.svg";
import NetCaseIcon from "../../../../../assets/storeIcon/netCase.svg";
import PandoraIcon from "../../../../../assets/storeIcon/pandora.svg";
import PelotonIcon from "../../../../../assets/storeIcon/peloton.svg";
import QobuzIcon from "../../../../../assets/storeIcon/qobuz.svg";
import SaavnIcon from "../../../../../assets/storeIcon/saavn.svg";
import SodaMusicIcon from "../../../../../assets/storeIcon/sodaMusic.svg";
import SoundcloudIcon from "../../../../../assets/storeIcon/soundcloud.svg";
import SoundexIcon from "../../../../../assets/storeIcon/soundex.svg";
import SpotifyIcon from "../../../../../assets/storeIcon/spotify.svg";
import SupernaturalIcon from "../../../../../assets/storeIcon/supernatural.svg";
import TaobaoIcon from "../../../../../assets/storeIcon/taobao.svg";
import TencentIcon from "../../../../../assets/storeIcon/tencent.svg";
import TidalIcon from "../../../../../assets/storeIcon/tidal.svg";
import TiktokIcon from "../../../../../assets/storeIcon/tiktok.svg";
import TunedGlobalIcon from "../../../../../assets/storeIcon/tunedGlobal.svg";
import UdioIcon from "../../../../../assets/storeIcon/udio.svg";
import YangoPlayIcon from "../../../../../assets/storeIcon/yangoPlay.svg";
import YoutubeMusicIcon from "../../../../../assets/storeIcon/youtubeMusic.svg";

export const genresList = [
  "Alternative",
  "Alternative/Experimental",
  "Alternative/Gothic",
  "Alternative/Grunge",
  "Alternative/Indie Pop",
  "Alternative/Indie Rock",
  "Alternative/Rock",
  "Ambient/New Age",
  "Ambient/New Age/Meditation",
  "Blues",
  "Blues/Contemporary Blues",
  "Blues/New Orleans Blues",
  "Blues/Traditional Blues",
  "Children's Music",
  "Children's Music/Classic",
  "Children's Music/Holiday",
  "Children's Music/Stories",
  "Classical",
  "Classical/Antique",
  "Classical/Baroque",
  "Classical/Chamber",
  "Classical/Concert",
  "Classical/Modern Compositions",
  "Classical/Opera",
  "Classical/Orchestral",
  "Classical/Piano",
  "Classical/Romantic",
  "Comedy",
  "Country",
  "Country/Bluegrass",
  "Country/Contemporary",
  "Country/Honky Tonk",
  "Country/Nashville",
  "Country/Pop",
  "Country/Square Dance",
  "Easy Listening",
  "Easy Listening/Bar Jazz/Cocktail",
  "Easy Listening/Bossa Nova",
  "Easy Listening/Lounge",
  "Easy Listening/Traditional",
  "Electronic",
  "Electronic/Acid House",
  "Electronic/Breaks",
  "Electronic/Broken beat",
  "Electronic/Chill Out",
  "Electronic/DJ Tools/Sample Packs",
  "Electronic/Dance",
  "Electronic/Deep House",
  "Electronic/Downtempo - experimental",
  "Electronic/Drum & Bass",
  "Electronic/Dub/Reggae/Dancehall",
  "Electronic/Dubstep/Grime",
  "Electronic/Electro House",
  "Electronic/Glitch Hop",
  "Electronic/Hard Dance",
  "Electronic/Hard Techno",
  "Electronic/Hardcore",
  "Electronic/Hardstyle",
  "Electronic/House",
  "Electronic/Indie Dance/Nu Disco",
  "Electronic/Jazz",
  "Electronic/Minimal",
  "Electronic/Pop Trance",
  "Electronic/Progressive House",
  "Electronic/Psy-Trance",
  "Electronic/Tech House",
  "Electronic/Techno",
  "Electronic/Trance",
  "Electronic/Trip Hop",
  "Experimental",
  "Fitness&Workout",
  "Flamenco",
  "Folk",
  "Funk/R&B",
  "Hip-Hop/Rap",
  "Hip-Hop/Rap/Gangsta & Hardcore",
  "Holiday/Christmas",
  "Inspirational",
  "Jazz",
  "Jazz/Bebop",
  "Jazz/Big Band",
  "Jazz/Brazilian Jazz",
  "Jazz/Classic",
  "Jazz/Contemporary",
  "Jazz/Dixie/Rag Time",
  "Jazz/Free Jazz",
  "Jazz/Fusion",
  "Jazz/Jazz Funk",
  "Jazz/Latin Jazz",
  "Jazz/Nu Jazz/Acid Jazz",
  "Jazz/Smooth Jazz",
  "Jazz/Swing",
  "Jazz/Traditional",
  "Jazz/World",
  "Karaoke",
  "Latin",
  "Latin/Bachata",
  "Latin/Banda",
  "Latin/Big Band",
  "Latin/Bolero",
  "Latin/Bossa Nova",
  "Latin/Brasil/Tropical",
  "Latin/Christian",
  "Latin/Conjunto",
  "Latin/Corridos",
  "Latin/Cuban",
  "Latin/Cumbia",
  "Latin/Duranguense",
  "Latin/Electronica",
  "Latin/Grupero",
  "Latin/Hip Hop",
  "Latin/Latin Rap",
  "Latin/Mambo",
  "Latin/Mariachi",
  "Latin/Norteño",
  "Latin/Pop",
  "Latin/Ranchera",
  "Latin/Reggaeton",
  "Latin/Regional Mexicano",
  "Latin/Rock en Español",
  "Latin/Salsa",
  "Latin/Salsa/Merengue",
  "Latin/Sierreño",
  "Latin/Sonidero",
  "Latin/Tango",
  "Latin/Tejano",
  "Latin/Tierra Caliente",
  "Latin/Traditional Mexican",
  "Latin/Vallenato",
  "New Age",
  "Pop",
  "Pop/Contemporary/Adult",
  "Pop/J-Pop",
  "Pop/K-Pop",
  "Pop/Mandopop",
  "Pop/Singer Songwriter",
  "Punk",
  "R&B",
  "Reggae",
  "Rock",
  "Rock/Black Metal",
  "Rock/Blues-Rock",
  "Rock/Brit-Pop",
  "Rock/British Invasion",
  "Rock/Chinese Rock",
  "Rock/Classic",
  "Rock/Death Metal",
  "Rock/Glam Rock",
  "Rock/Hair Metal",
  "Rock/Hard Rock",
  "Rock/Heavy Metal",
  "Rock/Jam Bands",
  "Rock/Korean Rock",
  "Rock/Progressive",
  "Rock/Psychedelic",
  "Rock/Rock 'n' Roll",
  "Rock/Rockabilly",
  "Rock/Russian Rock",
  "Rock/Singer/Songwriter",
  "Rock/Southern Rock",
  "Rock/Surf",
  "Rock/Tex-Mex",
  "Rock/Turkish Rock",
  "Ska",
  "Soul",
  "Soundtrack",
  "Soundtrack/Anime",
  "Soundtrack/Musical",
  "Soundtrack/TV",
  "Spiritual",
  "Spiritual/Christian",
  "Spiritual/Gospel",
  "Spiritual/Gregorian",
  "Spiritual/India",
  "Spiritual/Judaica",
  "Spiritual/World",
  "Spoken Word/Speeches",
  "Trap",
  "Trap/Future Bass",
  "Trap/Future Bass/Twerk",
  "Vocal/Nostalgia",
  "World",
  "World/African",
  "World/African/African Dancehall",
  "World/African/African Reggae",
  "World/African/Afrikaans",
  "World/African/Afro-Beat",
  "World/African/Afro-Folk",
  "World/African/Afro-Fusion",
  "World/African/Afro-House",
  "World/African/Afro-Pop",
  "World/African/Afro-Soul",
  "World/African/Afrobeats",
  "World/African/Alte",
  "World/African/Amapiano",
  "World/African/Benga",
  "World/African/Bongo-Flava",
  "World/African/Coupé-Décalé",
  "World/African/Gqom",
  "World/African/Highlife",
  "World/African/Kizomba",
  "World/African/Kuduro",
  "World/African/Kwaito",
  "World/African/Maskandi",
  "World/African/Mbalax",
  "World/African/Ndombolo",
  "World/African/Shangaan Electro",
  "World/African/Soukous",
  "World/African/Taarab",
  "World/African/Zouglou",
  "World/Americas/Argentina",
  "World/Americas/Brazilian",
  "World/Americas/Brazilian/Axé",
  "World/Americas/Brazilian/Baile Funk",
  "World/Americas/Brazilian/Black Music",
  "World/Americas/Brazilian/Bossa Nova",
  "World/Americas/Brazilian/Chorinho",
  "World/Americas/Brazilian/Folk",
  "World/Americas/Brazilian/Forró",
  "World/Americas/Brazilian/Frevo",
  "World/Americas/Brazilian/Funk Carioca",
  "World/Americas/Brazilian/MPB",
  "World/Americas/Brazilian/Marchinha",
  "World/Americas/Brazilian/Pagode",
  "World/Americas/Brazilian/Samba",
  "World/Americas/Brazilian/Samba-Rock",
  "World/Americas/Brazilian/Samba-de-Raiz",
  "World/Americas/Brazilian/Samba-enredo",
  "World/Americas/Brazilian/Sambalanço",
  "World/Americas/Brazilian/Sertanejo",
  "World/Americas/Cajun-Creole",
  "World/Americas/Calypso",
  "World/Americas/Colombia",
  "World/Americas/Cuba-Caribbean",
  "World/Americas/Mexican",
  "World/Americas/North-American",
  "World/Americas/Panama",
  "World/Americas/Peru",
  "World/Americas/South-American",
  "World/Arabic",
  "World/Asian/Central Asia",
  "World/Asian/China",
  "World/Asian/Indian",
  "World/Asian/Indian/Assamese",
  "World/Asian/Indian/Bengali",
  "World/Asian/Indian/Bengali/Rabindra Sangeet",
  "World/Asian/Indian/Bhojpuri",
  "World/Asian/Indian/Bollywood",
  "World/Asian/Indian/Carnatic Classical",
  "World/Asian/Indian/Folk",
  "World/Asian/Indian/Hindi",
  "World/Asian/Indian/Hindi/Ghazals",
  "World/Asian/Indian/Hindi/Indie",
  "World/Asian/Indian/Hindi/Playback",
  "World/Asian/Indian/Hindi/Sufi",
  "World/Asian/Indian/Hindi/Tagore",
  "World/Asian/Indian/Hindi/Tributes",
  "World/Asian/Indian/Hindi/World Fusion",
  "World/Asian/Indian/Kannada",
  "World/Asian/Indian/Kashmiri",
  "World/Asian/Indian/Kerala",
  "World/Asian/Indian/Malayalam",
  "World/Asian/Indian/Marathi",
  "World/Asian/Indian/Odia",
  "World/Asian/Indian/Punjabi",
  "World/Asian/Indian/Tamil",
  "World/Asian/Indian/Telugu",
  "World/Asian/Indian/Uttarakhand",
  "World/Asian/India",
  "World/Asian/Japan",
  "World/Asian/Korea",
  "World/Asian/Mongolian",
  "World/Asian/Middle Eastern",
  "World/Asian/Turkey",
  "World/European",
  "World/European/Balkan",
  "World/European/Belarus",
  "World/European/Bulgarian",
  "World/European/Celtic",
  "World/European/Celtic/Irish",
  "World/European/Celtic/Scottish",
  "World/European/Celtic/Welsh",
  "World/European/English",
  "World/European/Fado",
  "World/European/French",
  "World/European/German",
  "World/European/Greek",
  "World/European/Italian",
  "World/European/Nordic",
  "World/European/Portuguese",
  "World/European/Russian",
];

export const rolesList = [
  "Primary Artist",
  "Featured Artist",
  "Composer",
  "Lyricist",
  "Producer",
  "Accordion",
  "Actor",
  "Adapter",
  "Arranger",
  "Assistant Engineer",
  "Background Vocal",
  "Banjo",
  "Bass Guitar",
  "Bassoon",
  "Bells",
  "Cello",
  "Choir",
  "Clarinet",
  "Co-Producer",
  "Conductor",
  "Drums",
  "Ensemble",
  "Fiddle",
  "Flute",
  "Graphic Design",
  "Guitar",
  "Harmonica",
  "Harp",
  "Horn",
  "Keyboards",
  "Lute",
  "Mastering Engineer",
  "Metallophone",
  "Mixing Engineer",
  "Oboe",
  "Orchestra",
  "Organ",
  "Other Performer",
  "Percussion",
  "Piano",
  "Programming",
  "Publisher",
  "Rap",
  "Recorder",
  "Recording Engineer",
  "Remixer",
  "Saxophone",
  "Synthesizer",
  "Tambourine",
  "Trombone",
  "Trumpet",
  "Viola",
  "Viola de Gamba",
  "Violin",
  "Vocals",
  "Whistle",
  "Xylophone",
];

export const languagesList = [
  "English",
  "Spanish",
  "Afrikaans",
  "Amharic",
  "Arabic",
  "Arabic - Egyptian",
  "Arabic - Moroccan",
  "Armenian",
  "Assamese",
  "Azerbaijani",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bhojpuri",
  "Bosnian",
  "Bulgarian",
  "Cambodian",
  "Catalan",
  "Chechen",
  "Chinese - Cantonese",
  "Chinese - Hakka",
  "Chinese - Mandarin",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "Estonian",
  "Filipino",
  "Finnish",
  "French",
  "Galician",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Haitian Creole",
  "Haryanvi",
  "Hawaiian",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Igbo",
  "Indonesian",
  "Irish",
  "Italian",
  "Japanese",
  "Kannada",
  "Kazakh",
  "Konkani",
  "Korean",
  "Kurdish",
  "Lao",
  "Latin",
  "Latvian",
  "Lingala",
  "Lithuanian",
  "Luganda",
  "Macedonian",
  "Malay",
  "Malayalam",
  "Maori",
  "Marathi",
  "Mongolian",
  "Nepali",
  "Norwegian",
  "Oriya",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Rajasthani",
  "Romanian",
  "Russian",
  "Samoan",
  "Sanskrit",
  "Sepedi",
  "Serbian",
  "Shona",
  "Slovak",
  "Slovene",
  "Sotho",
  "Swahili",
  "Swedish",
  "Tagalog",
  "Tahitian",
  "Tamazight",
  "Tamil",
  "Telugu",
  "Thai",
  "Tsonga",
  "Tswana",
  "Turkish",
  "Twi",
  "Ukrainian",
  "Urdu",
  "Venda",
  "Vietnamese",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zulu",
];

export const priceCategories = ["Budget", "Mid", "Full", "Premium"];

export const musicStores = [
  { id: "spotify", name: "Spotify", subText: "SPO", logo: SpotifyIcon },
  { id: "youtubeMusic", name: "Youtube Music", subText: "YTM", logo: YoutubeMusicIcon },
  { id: "appleMusic", name: "Apple Music", subText: "APM", logo: AppleMusicIcon },
  { id: "amazonMusic", name: "Amazon Music", subText: "AMZ", logo: AmazonMusicIcon },
  { id: "anghami", name: "Anghami", subText: "ANG", logo: AnghamiIcon },
  { id: "audibleMagic", name: "Audible Magic", subText: "AUM", logo: AudibleMagicIcon },
  { id: "awa", name: "AWA", subText: "AWA", logo: AwaIcon },
  { id: "beatport", name: "Beatport", subText: "BTP", logo: BeatportIcon },
  { id: "boomplay", name: "Boomplay", subText: "BMP", logo: BoomplayIcon },
  { id: "claroMusic", name: "Claro Música", subText: "CLR", logo: ClaroMusicIcon },
  { id: "deezer", name: "Deezer", subText: "DEE", logo: DeezerIcon },
  { id: "douYin", name: "Douyin", subText: "DY", logo: DouYinIcon },
  { id: "flo", name: "FLO", subText: "FLO", logo: FloIcon },
  { id: "iHeart", name: "iHeartRadio", subText: "IHR", logo: IHeartIcon },
  { id: "joox", name: "JOOX", subText: "JOX", logo: JooxIcon },
  { id: "kDigital", name: "K-Digital", subText: "KDM", logo: KDigitalIcon },
  { id: "kanjian", name: "Kanjian", subText: "KAN", logo: KanjianIcon },
  { id: "kkbox", name: "KKBOX", subText: "KKX", logo: KkboxIcon },
  { id: "lickd", name: "Lickd", subText: "LKD", logo: LickdIcon },
  { id: "lissen", name: "Lissen", subText: "LIS", logo: LissenIcon },
  { id: "massive", name: "Massive Music", subText: "MSV", logo: MassiveIcon },
  { id: "meta", name: "Meta (FB / Instagram)", subText: "META", logo: MetaIcon },
  { id: "mixCloud", name: "Mixcloud", subText: "MXC", logo: MixCloudIcon },
  { id: "netCase", name: "NetEase Cloud Music", subText: "NTE", logo: NetCaseIcon },
  { id: "pandora", name: "Pandora", subText: "PND", logo: PandoraIcon },
  { id: "peloton", name: "Peloton", subText: "PLT", logo: PelotonIcon },
  { id: "qobuz", name: "Qobuz", subText: "QBZ", logo: QobuzIcon },
  { id: "saavn", name: "JioSaavn", subText: "JSV", logo: SaavnIcon },
  { id: "sodaMusic", name: "Soda Music", subText: "SDA", logo: SodaMusicIcon },
  { id: "soundcloud", name: "Soundcloud", subText: "SND", logo: SoundcloudIcon },
  { id: "soundex", name: "SoundEx", subText: "SDX", logo: SoundexIcon },
  { id: "supernatural", name: "Supernatural", subText: "SUPNAT", logo: SupernaturalIcon },
  { id: "taobao", name: "Taobao", subText: "XIAM", logo: TaobaoIcon },
  { id: "tencent", name: "Tencent", subText: "TNCT", logo: TencentIcon },
  { id: "tidal", name: "Tidal", subText: "WIMP", logo: TidalIcon },
  { id: "tiktok", name: "TikTok", subText: "TIKTOK", logo: TiktokIcon },
  { id: "tunedGlobal", name: "Tuned Global", subText: "TGLOBAL", logo: TunedGlobalIcon },
  { id: "udio", name: "Udio", subText: "UDIO", logo: UdioIcon },
  { id: "yangoPlay", name: "Yango Play", subText: "YGP", logo: YangoPlayIcon },
];
