export const genresList = [
  "Alternative",
  "Alternative/Experimental",
  "Alternative/Gothic",
  "Alternative/Grunge",
  "Alternative/Indie Pop",
  "Alternative/Indie Rock",
  "Alternative/Rock",
  "Ambient/New Age",
  "Ambient/New Age/Meditation",
  "Blues",
  "Blues/Contemporary Blues",
  "Blues/New Orleans Blues",
  "Blues/Traditional Blues",
  "Children's Music",
  "Children's Music/Classic",
  "Children's Music/Holiday",
  "Children's Music/Stories",
  "Classical",
  "Classical/Antique",
  "Classical/Baroque",
  "Classical/Chamber",
  "Classical/Concert",
  "Classical/Modern Compositions",
  "Classical/Opera",
  "Classical/Orchestral",
  "Classical/Piano",
  "Classical/Romantic",
  "Comedy",
  "Country",
  "Country/Bluegrass",
  "Country/Contemporary",
  "Country/Honky Tonk",
  "Country/Nashville",
  "Country/Pop",
  "Country/Square Dance",
  "Easy Listening",
  "Easy Listening/Bar Jazz/Cocktail",
  "Easy Listening/Bossa Nova",
  "Easy Listening/Lounge",
  "Easy Listening/Traditional",
  "Electronic",
  "Electronic/Acid House",
  "Electronic/Breaks",
  "Electronic/Broken beat",
  "Electronic/Chill Out",
  "Electronic/DJ Tools/Sample Packs",
  "Electronic/Dance",
  "Electronic/Deep House",
  "Electronic/Downtempo - experimental",
  "Electronic/Drum & Bass",
  "Electronic/Dub/Reggae/Dancehall",
  "Electronic/Dubstep/Grime",
  "Electronic/Electro House",
  "Electronic/Glitch Hop",
  "Electronic/Hard Dance",
  "Electronic/Hard Techno",
  "Electronic/Hardcore",
  "Electronic/Hardstyle",
  "Electronic/House",
  "Electronic/Indie Dance/Nu Disco",
  "Electronic/Jazz",
  "Electronic/Minimal",
  "Electronic/Pop Trance",
  "Electronic/Progressive House",
  "Electronic/Psy-Trance",
  "Electronic/Tech House",
  "Electronic/Techno",
  "Electronic/Trance",
  "Electronic/Trip Hop",
  "Experimental",
  "Fitness&Workout",
  "Flamenco",
  "Folk",
  "Funk/R&B",
  "Hip-Hop/Rap",
  "Hip-Hop/Rap/Gangsta & Hardcore",
  "Holiday/Christmas",
  "Inspirational",
  "Jazz",
  "Jazz/Bebop",
  "Jazz/Big Band",
  "Jazz/Brazilian Jazz",
  "Jazz/Classic",
  "Jazz/Contemporary",
  "Jazz/Dixie/Rag Time",
  "Jazz/Free Jazz",
  "Jazz/Fusion",
  "Jazz/Jazz Funk",
  "Jazz/Latin Jazz",
  "Jazz/Nu Jazz/Acid Jazz",
  "Jazz/Smooth Jazz",
  "Jazz/Swing",
  "Jazz/Traditional",
  "Jazz/World",
  "Karaoke",
  "Latin",
  "Latin/Bachata",
  "Latin/Banda",
  "Latin/Big Band",
  "Latin/Bolero",
  "Latin/Bossa Nova",
  "Latin/Brasil/Tropical",
  "Latin/Christian",
  "Latin/Conjunto",
  "Latin/Corridos",
  "Latin/Cuban",
  "Latin/Cumbia",
  "Latin/Duranguense",
  "Latin/Electronica",
  "Latin/Grupero",
  "Latin/Hip Hop",
  "Latin/Latin Rap",
  "Latin/Mambo",
  "Latin/Mariachi",
  "Latin/Norteño",
  "Latin/Pop",
  "Latin/Ranchera",
  "Latin/Reggaeton",
  "Latin/Regional Mexicano",
  "Latin/Rock en Español",
  "Latin/Salsa",
  "Latin/Salsa/Merengue",
  "Latin/Sierreño",
  "Latin/Sonidero",
  "Latin/Tango",
  "Latin/Tejano",
  "Latin/Tierra Caliente",
  "Latin/Traditional Mexican",
  "Latin/Vallenato",
  "New Age",
  "Pop",
  "Pop/Contemporary/Adult",
  "Pop/J-Pop",
  "Pop/K-Pop",
  "Pop/Mandopop",
  "Pop/Singer Songwriter",
  "Punk",
  "R&B",
  "Reggae",
  "Rock",
  "Rock/Black Metal",
  "Rock/Blues-Rock",
  "Rock/Brit-Pop",
  "Rock/British Invasion",
  "Rock/Chinese Rock",
  "Rock/Classic",
  "Rock/Death Metal",
  "Rock/Glam Rock",
  "Rock/Hair Metal",
  "Rock/Hard Rock",
  "Rock/Heavy Metal",
  "Rock/Jam Bands",
  "Rock/Korean Rock",
  "Rock/Progressive",
  "Rock/Psychedelic",
  "Rock/Rock 'n' Roll",
  "Rock/Rockabilly",
  "Rock/Russian Rock",
  "Rock/Singer/Songwriter",
  "Rock/Southern Rock",
  "Rock/Surf",
  "Rock/Tex-Mex",
  "Rock/Turkish Rock",
  "Ska",
  "Soul",
  "Soundtrack",
  "Soundtrack/Anime",
  "Soundtrack/Musical",
  "Soundtrack/TV",
  "Spiritual",
  "Spiritual/Christian",
  "Spiritual/Gospel",
  "Spiritual/Gregorian",
  "Spiritual/India",
  "Spiritual/Judaica",
  "Spiritual/World",
  "Spoken Word/Speeches",
  "Trap",
  "Trap/Future Bass",
  "Trap/Future Bass/Twerk",
  "Vocal/Nostalgia",
  "World",
  "World/African",
  "World/African/African Dancehall",
  "World/African/African Reggae",
  "World/African/Afrikaans",
  "World/African/Afro-Beat",
  "World/African/Afro-Folk",
  "World/African/Afro-Fusion",
  "World/African/Afro-House",
  "World/African/Afro-Pop",
  "World/African/Afro-Soul",
  "World/African/Afrobeats",
  "World/African/Alte",
  "World/African/Amapiano",
  "World/African/Benga",
  "World/African/Bongo-Flava",
  "World/African/Coupé-Décalé",
  "World/African/Gqom",
  "World/African/Highlife",
  "World/African/Kizomba",
  "World/African/Kuduro",
  "World/African/Kwaito",
  "World/African/Maskandi",
  "World/African/Mbalax",
  "World/African/Ndombolo",
  "World/African/Shangaan Electro",
  "World/African/Soukous",
  "World/African/Taarab",
  "World/African/Zouglou",
  "World/Americas/Argentina",
  "World/Americas/Brazilian",
  "World/Americas/Brazilian/Axé",
  "World/Americas/Brazilian/Baile Funk",
  "World/Americas/Brazilian/Black Music",
  "World/Americas/Brazilian/Bossa Nova",
  "World/Americas/Brazilian/Chorinho",
  "World/Americas/Brazilian/Folk",
  "World/Americas/Brazilian/Forró",
  "World/Americas/Brazilian/Frevo",
  "World/Americas/Brazilian/Funk Carioca",
  "World/Americas/Brazilian/MPB",
  "World/Americas/Brazilian/Marchinha",
  "World/Americas/Brazilian/Pagode",
  "World/Americas/Brazilian/Samba",
  "World/Americas/Brazilian/Samba-Rock",
  "World/Americas/Brazilian/Samba-de-Raiz",
  "World/Americas/Brazilian/Samba-enredo",
  "World/Americas/Brazilian/Sambalanço",
  "World/Americas/Brazilian/Sertanejo",
  "World/Americas/Cajun-Creole",
  "World/Americas/Calypso",
  "World/Americas/Colombia",
  "World/Americas/Cuba-Caribbean",
  "World/Americas/Mexican",
  "World/Americas/North-American",
  "World/Americas/Panama",
  "World/Americas/Peru",
  "World/Americas/South-American",
  "World/Arabic",
  "World/Asian/Central Asia",
  "World/Asian/China",
  "World/Asian/Indian",
  "World/Asian/Indian/Assamese",
  "World/Asian/Indian/Bengali",
  "World/Asian/Indian/Bengali/Rabindra Sangeet",
  "World/Asian/Indian/Bhojpuri",
  "World/Asian/Indian/Bollywood",
  "World/Asian/Indian/Carnatic Classical",
  "World/Asian/Indian/Folk",
  "World/Asian/Indian/Hindi",
  "World/Asian/Indian/Hindi/Ghazals",
  "World/Asian/Indian/Hindi/Indie",
  "World/Asian/Indian/Hindi/Playback",
  "World/Asian/Indian/Hindi/Sufi",
  "World/Asian/Indian/Hindi/Tagore",
  "World/Asian/Indian/Hindi/Tributes",
  "World/Asian/Indian/Hindi/World Fusion",
  "World/Asian/Indian/Kannada",
  "World/Asian/Indian/Kashmiri",
  "World/Asian/Indian/Kerala",
  "World/Asian/Indian/Malayalam",
  "World/Asian/Indian/Marathi",
  "World/Asian/Indian/Odia",
  "World/Asian/Indian/Punjabi",
  "World/Asian/Indian/Tamil",
  "World/Asian/Indian/Telugu",
  "World/Asian/Indian/Uttarakhand",
  "World/Asian/India",
  "World/Asian/Japan",
  "World/Asian/Korea",
  "World/Asian/Mongolian",
  "World/Asian/Middle Eastern",
  "World/Asian/Turkey",
  "World/European",
  "World/European/Balkan",
  "World/European/Belarus",
  "World/European/Bulgarian",
  "World/European/Celtic",
  "World/European/Celtic/Irish",
  "World/European/Celtic/Scottish",
  "World/European/Celtic/Welsh",
  "World/European/English",
  "World/European/Fado",
  "World/European/French",
  "World/European/German",
  "World/European/Greek",
  "World/European/Italian",
  "World/European/Nordic",
  "World/European/Portuguese",
  "World/European/Russian",
];

export const rolesList = [
  "Primary Artist",
  "Featured Artist",
  "Composer",
  "Lyricist",
  "Producer",
  "Accordion",
  "Actor",
  "Adapter",
  "Arranger",
  "Assistant Engineer",
  "Background Vocal",
  "Banjo",
  "Bass Guitar",
  "Bassoon",
  "Bells",
  "Cello",
  "Choir",
  "Clarinet",
  "Co-Producer",
  "Conductor",
  "Drums",
  "Ensemble",
  "Fiddle",
  "Flute",
  "Graphic Design",
  "Guitar",
  "Harmonica",
  "Harp",
  "Horn",
  "Keyboards",
  "Lute",
  "Mastering Engineer",
  "Metallophone",
  "Mixing Engineer",
  "Oboe",
  "Orchestra",
  "Organ",
  "Other Performer",
  "Percussion",
  "Piano",
  "Programming",
  "Publisher",
  "Rap",
  "Recorder",
  "Recording Engineer",
  "Remixer",
  "Saxophone",
  "Synthesizer",
  "Tambourine",
  "Trombone",
  "Trumpet",
  "Viola",
  "Viola de Gamba",
  "Violin",
  "Vocals",
  "Whistle",
  "Xylophone",
];

export const languagesList = [
  "English",
  "Spanish",
  "Afrikaans",
  "Amharic",
  "Arabic",
  "Arabic - Egyptian",
  "Arabic - Moroccan",
  "Armenian",
  "Assamese",
  "Azerbaijani",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bhojpuri",
  "Bosnian",
  "Bulgarian",
  "Cambodian",
  "Catalan",
  "Chechen",
  "Chinese - Cantonese",
  "Chinese - Hakka",
  "Chinese - Mandarin",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "Estonian",
  "Filipino",
  "Finnish",
  "French",
  "Galician",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Haitian Creole",
  "Haryanvi",
  "Hawaiian",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Igbo",
  "Indonesian",
  "Irish",
  "Italian",
  "Japanese",
  "Kannada",
  "Kazakh",
  "Konkani",
  "Korean",
  "Kurdish",
  "Lao",
  "Latin",
  "Latvian",
  "Lingala",
  "Lithuanian",
  "Luganda",
  "Macedonian",
  "Malay",
  "Malayalam",
  "Maori",
  "Marathi",
  "Mongolian",
  "Nepali",
  "Norwegian",
  "Oriya",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Rajasthani",
  "Romanian",
  "Russian",
  "Samoan",
  "Sanskrit",
  "Sepedi",
  "Serbian",
  "Shona",
  "Slovak",
  "Slovene",
  "Sotho",
  "Swahili",
  "Swedish",
  "Tagalog",
  "Tahitian",
  "Tamazight",
  "Tamil",
  "Telugu",
  "Thai",
  "Tsonga",
  "Tswana",
  "Turkish",
  "Twi",
  "Ukrainian",
  "Urdu",
  "Venda",
  "Vietnamese",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zulu",
];

export const priceCategories = ["Budget", "Mid", "Full", "Premium"];

export const timeZones = [
  "UTC",
  "IST (India Standard Time)",
  "EST (Eastern Standard Time)",
  "PST (Pacific Standard Time)",
  "CET (Central European Time)",
  "GMT (Greenwich Mean Time)",
];

export const musicStores = [
  "Spotify",
  "Youtube Music",
  "Apple Music",
  "Amoeba Music",
  "Local Music Store",
];
